myEnvironments/beltreviewer/apps/beltReviewerApp/urls.py
from django.conf.urls import url
from views import dashboard, addBookReview, addReview, bookInfo, userInfo, delete, logout
app_name= "beltReviewerApp"
urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^addBookReview$', addBookReview, name='addBookReview'),
    url(r'^addReview/(?P<book_id>\d+)$', addReview, name='addReview'),
    url(r'^bookInfo/(?P<book_id>\d+)$', bookInfo, name='bookInfo'),
    url(r'^userInfo/(?P<id>\d+)$', userInfo, name='userInfo'),
    url(r'^delete/(?P<id>\d+)$', delete, name='delete'),
    url(r'^logout$', logout, name='logout')
]

myEnvironments/beltreviewer/beltreviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^dashboard/', include('apps.beltReviewerApp.urls', namespace="beltReviewerApp")),
    url(r'^', include('apps.loginAndRegistration.urls', namespace="loginAndRegistration")),
]

myEnvironments/beltreviewer/apps/beltReviewerApp/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginAndRegistration.models import User

class BookManager(models.Manager):
    def add_book(self, postData):
        flag=False
        errors=[]
        if len(postData['title'])<1:
            flag=True
            errors.append("Destination cannot be empty!")
        if len(postData['author1']) and len(postData['author2'])<0:
            flag=True
            errors.append("You can have to have an author!")
        if len(postData['author1']) and len(postData['author2'])>1:
            flag=True
            errors.append("You can only have one author!")
        if postData['review'] < 1:
            flag=True
            errors.append("Review cannot be empty!")
        if postData['rating']< 1:
            flag=True
            errors.append("Rating has to be between 1 & 5!")
        if not flag:
            addBook= Book.objects.create(title=postData['title'])
            return (flag, addBook)
        return (flag, errors)
class AuthorManager(models.Manager):
    def add_author(self, postData, book_id):
        flag=False
        if len(postData['author1'])>1:
            author=postData['author1']
        else:
            author=postData['author2']
            name=Author.objects.all()
            for x in name:
                if author==x.author:
                    id=x.id
                    addAuthor= Author.objects.create(id=id, book_id=book_id)
                    return (flag, addAuthor)
            addAuthor= Author.objects.create(author=author, book_id=book_id)
            return (flag, addAuthor)

class BookReviewManager(models.Manager):
    def add_review_to_book(self,postData, book_id):
        flag=False
        errors=[]
        if postData['review']<1:
            flag=True
            errors.append("Review cannot be empty!")
        if postData['rating']<1:
            flag=True
            errors.append("Rating has to be between 1 & 5!")
        if not flag:
            addBookReview= BookReview.objects.create(rating=postData['rating'], review=postData['review'], book_reviewer_id=postData['user'], book_title_id=book_id)
            return (flag, addBookReview)
        return (flag, errors)

class Book(models.Model):
    title = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects= BookManager()

class Author(models.Model):
    book=models.ForeignKey('Book')
    author=models.CharField(max_length=500)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects=AuthorManager()

class BookReview(models.Model):
    rating=models.IntegerField()
    review=models.TextField()
    book_reviewer= models.ForeignKey(User, related_name="book_reviewer")
    book_title = models.ForeignKey(Book, related_name="book_title")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects=BookReviewManager()

myEnvironments/beltreviewer/apps/beltReviewerApp/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from datetime import datetime
from django.core.urlresolvers import reverse
from ..loginAndRegistration.models import User
from .models import Book, Author, BookReview

def existingUser(request):
    return 'name' in request.session

def dashboard(request):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    recent= BookReview.objects.all().order_by('-created_at')[:3]
    allReviews=BookReview.objects.all().order_by('-created_at')[3:]
    context={
        "recents": recent,
        "allReviews": allReviews
    }
    return render(request, "beltReviewer/index.html",context)

def addBookReview(request):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    if request.method=="GET":
        context={
            "authors": Author.objects.all()
        }
        return render(request, 'beltReviewer/addBook.html', context)
    if request.method=="POST":
        postData={
            "user":request.session['user_id'],
            "author1": request.POST['author1'],
            "author2":request.POST['author2'],
            "title": request.POST['title'],
            "review":request.POST['review'],
            "rating": request.POST['rating'],
        }
        print postData
        results=Book.objects.add_book(postData)
        if results[0]:
            for err in results[1]:
                messages.error(request,err)
            return render(request, 'beltReviewer/addBook.html')
        else:
            book=Book.objects.last()
            book_id=book.id
            context={
                "book_id": book_id,
                "book": book
            }
            results2=Author.objects.add_author(postData, book_id)
            user_id=request.session['user_id']
            results3=BookReview.objects.add_review_to_book(postData, book_id)
            return render(request, 'beltReviewer/details.html', context)

def addReview(request, book_id):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    postData={
        "user":request.session['user_id'],
        "book_id": book_id,
        "review":request.POST['review'],
        "rating": request.POST['rating'],
    }
    results=BookReview.objects.add_review_to_book(postData, book_id)
    if results[0]:
        for err in results[1]:
            messages.error(request,err)

def bookInfo(request, book_id):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    if request.method=="GET":
        reviews=BookReview.objects.filter(book_title_id=book_id)
        context={
            "book": Book.objects.get(id=book_id),
            "reviews": reviews
            }
        return render(request, "beltReviewer/details.html", context)

def userInfo(request, id):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    user=User.objects.get(id=id)
    reviewer=BookReview.objects.filter(book_reviewer_id=id)
    # BookReview.objects.all().annotate(book_reviewer=.Count("id"))
    context={
        "user":user,
        "reviewer":reviewer
    }
    return render(request, 'beltReviewer/userinfo.html', context)

def delete(request, id):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    if BookReview.objects.get(id=id).delete():
        return redirect(reverse('beltReviewerApp:bookInfo'))

def logout(request):
    if not existingUser(request):
        return redirect(reverse("loginAndRegistration:index"))
    request.session.pop('user_id')
    request.session.pop('name')
    request.session.pop('alias')
    return redirect(reverse("loginAndRegistration:index"))

myEnvironments/beltreviewer/apps/beltReviewerApp/templates/beltReviewer/addBook.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Add Book and Review</title>
    <link rel="stylesheet" href="{% static 'beltReviewer/css/beltReviewer.css' %}" media="screen"  charset="utf-8">
</head>
<body>
<div id="wrapper">
    <div id="topright">
        <a href="{% url 'beltReviewerApp:dashboard' %}">Home</a>
        <a href="{% url 'beltReviewerApp:logout' %}">Logout</a>
    </div>
    <h1>Add A New Book Review:<h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class={{message.tags}} {% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{%url 'beltReviewerApp:addBookReview' %}" method='post'>
            {% csrf_token %}
            <p><label for="title">Book Title:</label>
            <input type="text" name="title" class="longer" required></p>

            <p><label for="author1">Choose from the list:</label>
                <select name="author1" class="longer">
                    <option value=""></option>
                    {% for author in authors %}
                    <option value="{{author.author}}">{{author.author}}</option>
                    {% endfor %}
                </select>
            </p>

            <p><label for="author2">Or add a new author:</label>
            <input class="longer" type="text" name="author2" ></p>

            <p><label for="review">Review:</label>
            <textarea rows="6" cols="50" name="review" required></textarea>

            <p><label for="rating">Rating:</label>
                <select name="rating" id="rating">
                    <option selected disabled hidden style='display: none' value=""></option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
             stars</p>
            <p><input type="submit" value="Add Book and Review"></p>
        </form>
</div>
</body>
</html>

myEnvironments/beltreviewer/apps/beltReviewerApp/templates/beltReviewer/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Book Info</title>
    <link rel="stylesheet" href="{% static 'beltReviewer/css/beltReviewer.css' %}"media="screen"  charset="utf-8">
</head>
<body>
    <div id="wrapper">
        <div id="topright">
            <a href="{% url 'beltReviewerApp:dashboard' %}">Home</a>
            <a href="{% url 'beltReviewerApp:logout' %}">Logout</a>
        </div>
        <h1>{{book.title}}</h1>
        <h2>{{book.author}}</h2>
        <h1>Reviews:</h1>
        {% for review in reviews %}
            <br></br>
            <p>Rating:{{review.rating}}</p>
            <p><a href="{% url 'beltReviewerApp:userInfo' id=review.book_reviewer.id %}">{{review.book_reviewer.alias}}</a> says: {{review.description}} </p>
            <p>Posted on {{review.created_at}}</p>

            {% if review.book_reviewer.id == request.session.user_id %}
            <p>{{review.id}}</p>
                <p><a href="{% url 'beltReviewerApp:delete' id=review.id %}">Delete this Review</a></p>
            {% endif %}
        {% endfor %}
        <h2>Add a Review:</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class={{message.tags}} {% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{%url 'beltReviewerApp:addReview' book_id=book.id %}" method='post'>
            <p>{{book.id}}</p>
            {% csrf_token %}
            <textarea rows="4" cols="40" name="review" required></textarea>
            <p><label for="rating">Rating:</label>
                <select name="rating" id="rating" required>
                    <option selected disabled hidden style='display: none' value=""></option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
            stars</p>
            <p><input type="submit" value="Submit Review"></p>
        </form>
    </div>
</body>
</html>

myEnvironments/beltreviewer/apps/beltReviewerApp/templates/beltReviewer/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'beltReviewer/css/beltReviewer.css' %}"media="screen"  charset="utf-8">
</head>
<body>
    <div id="wrapper">
        <div id="topright">
            <a href="{% url 'beltReviewerApp:addBookReview' %}" value="AddBookReview">Add Book and Review </a>
            <a href="{%url 'beltReviewerApp:logout'  %}">Logout</a>
        </div>
        <h1>Welcome, {{request.session.alias}}</h1>

        <h1>Recent Book Reviews:</h1>
        <div id="bookreviews">
            {% for recent in recents %}
            <p><a href="{% url 'beltReviewerApp:bookInfo' book_id=recent.book_title.id %}"> {{recent.book_title.title}}</a></p>
                <p>Rating: {{recent.rating}}/5</p>
                <p><a href="{% url 'beltReviewerApp:userInfo' id=recent.book_reviewer.id  %}">{{recent.book_reviewer.alias }}</a>: <em>{{recent.review}}</em></p>
                <p>{{recent.created_at }}</p>
            {% endfor %}
        </div>
        <div id="bottomstuff">
        <h1>Other Books with Reviews:</h1>
            {% for review in allReviews %}
                <p><a href="{% url 'beltReviewerApp:bookInfo' book_id=book_title.id %}"> {{review.book_title.title}}</a></p>
                <p>{{book_title.id }}</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>

myEnvironments/beltreviewer/apps/beltReviewerApp/templates/beltReviewer/userinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>User Info</title>
    <link rel="stylesheet" href="{% static 'beltReviewer/css/beltReviewer.css' %}"media="screen"  charset="utf-8">
</head>
<body>
    <div id="wrapper">
        <div id="topright">
            <a href="{% url 'beltReviewerApp:dashboard' %}">Home</a>
            <a href="{% url 'beltReviewerApp:addBookReview' %}">Add Book and Review </a>
            <a href="{%url 'beltReviewerApp:logout'  %}">Logout</a>
        </div>
        <h1>User Alias: {{user.alias}}</h1>
        <h3>{{user.name}}</h3>
        <h3>{{user.email}}</h3>
        <h3>Total Reviews: {{reviewer.count}}
        <h1>Posted Reviews on the following books:</h1>
            {% for review in reviewer %}
                <p><a href="{% url 'beltReviewerApp:bookInfo' book_id=review.book_title.id %}">
                     {{review.book_title.title}}</a></p>
            {% endfor %}

    </div>
</body>
</html>