myEnvironments/integration_project/apps/courses_app/urls.py
from django.conf.urls import url
from views import index, process, remove, delete, logout
app_name="courses_app"
urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^process$', process, name="process"),
    url(r'^remove(?P<id>\d+)$', remove, name="remove"),
    url(r'^delete/(?P<id>\d+)$', delete, name="delete"),
    url(r'^logout$', logout, name="logout"),
    # url(r'^dashboard$', dashboard, name="dashbaord")
]

myEnvironments/integration_project/integration_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginAndRegistration.urls', namespace="loginAndRegistration")),
    url(r'^dashboard/', include('apps.multiple_apps.urls', namespace="multiple_apps")),
    url(r'^survey/', include('apps.survey_form.urls', namespace="survey_form")),
    url(r'^courses/', include('apps.courses_app.urls', namespace="courses_app")),
]

myEnvironments/integration_project/apps/courses_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginAndRegistration.models import User

class CourseManager(models.Manager):
    def add_to_user(self, postData):
        course=self.get(id=postData['course'])
        user=User.objects.get(id=postData['user'])
        print user.first_name
        print "*"*50
        print "*"*50

class Course(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CourseManager()

myEnvironments/integration_project/apps/courses_app/views.py
from django.shortcuts import render, redirect
from .models import Course
from ..multiple_apps.models import User_Course
from django.urls import reverse

def index(request):
    context = {
        'courses': Course.objects.all()
        }
    return render(request, 'courses_app/index.html', context)

def process(request):
    Course.objects.create(name=request.POST['name'], description=request.POST['description'])
    return redirect(reverse("courses_app:index"))

def remove(request, id):
	context = {
	'courses': Course.objects.filter(id=id)
	}
	return render(request, "courses/delete.html", context)

def delete(request, id):
    delete = Course.objects.get(id=id)
    if 'yeabye' in request.POST:
        Course.objects.filter(id=id).delete()
        User_Course.objects.filter(course_id=id).delete()
        return redirect (reverse("courses_app:index"))
    else:
        return redirect(reverse("courses_app:index"))

def logout(request):
	request.session.pop('user_id')
	request.session.pop('name')
	return redirect('/')

myEnvironments/integration_project/apps/courses_app/templates/courses_app/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div id="container">
        <h1>Are you sure you want to delete the following course?</h1>

        <h3>Name: {{course.name}}</h3>
        <h3>Description: {{course.description}}</h3>
        <form action="{% url 'courses_app:delete' id=course.id %}" method='post'>
            {% csrf_token %}
            <input type="submit" value="No" name="nevermind">
            <input type="submit" value="Yes! I want to delete this." name="yeabye">
    </div>

</body>
</html>

myEnvironments/integration_project/apps/courses_app/templates/courses_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course</title>
</head>
<body>
    <div id="container">

        <h1>Add a new course</h1>
        <form action={% url "courses_app:process" %} method='post'>
            {% csrf_token %}
            Name:<input type="text" name="name">
            <br>
            Description:<input type="text" name="description"></textarea>
            <br>
            <input type="submit" value="Add">
        </form>
        <h3>Courses</h3>
        <table>
            <thead>
                <tr>
                    <td>Course Name</td><td>Description</td><td>Date Added</td><td>Actions</td>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                <td>{{course.name}}</td><td>{{course.description}}</td><td>{{course.created_at}}</td><td><a href='{%url "courses_app:remove" id=course.id %}'>Remove</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'multiple_apps:index'%}">Back to Dashboard</a>
</body>
</html>