myEnvironments/login_and_registrationDjango/apps/loginAndRegistration/urls.py
from django.conf.urls import url
from views import index, process, success, login, logout, delete
app_name= "loginAndRegistration"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^process$', process, name='process'),
    url(r'^success$', success, name='success'),
    url(r'^delete/(?P<id>\d+)$', delete, name='delete'),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout')
]

myEnvironments/login_and_registrationDjango/login_and_registrationDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginAndRegistration.urls', namespace="loginAndRegistration")),
]

myEnvironments/login_and_registrationDjango/apps/loginAndRegistration/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt

import re

EMAIL_REGEX=re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
FIRSTNAME_REGEX = re.compile(r'^[a-zA-Z]*$')
LASTNAME_REGEX = re.compile(r'^[a-zA-Z]*$')

class UserManager(models.Manager):
    def UserValidator(self, postData):
        flag=False
        errors=[]
        if len(postData['email']) <2:
            flag=True
            errors.append("Email cannot be empty!")
        if not EMAIL_REGEX.match(postData['email']):
            errors.append("Invalid email.")
            flag=True
        if len(postData['first_name']) < 2:
            errors.append("First name cannot be empty!")
            flag=True
        elif not FIRSTNAME_REGEX.match(postData['first_name']):
            errors.append("Invalid first name!")
            flat=True
        if len(postData['last_name']) < 2:
            flag=True
            errors.append("Last name cannot be empty!")
        elif not LASTNAME_REGEX.match(postData['last_name']):
            flag=True
            errors.append ("Invalid last name!")
        if len(postData['password'])<8:
            flag=True
            errors.append("Password length is invalid")
        if len(postData['password_confirmation']) < 1:
            errors.append("Confirm password cannot be empty!")
            flag=True
        if postData['password_confirmation'] != postData['password']:
            flag=True
            errors.append("Passwords do not match!")
        if not flag:
            pwhash= bcrypt.hashpw(postData['password'].encode(),bcrypt.gensalt())
            User.objects.create(
                first_name=postData['first_name'],
                last_name=postData['last_name'],
                email=postData['email'],
                password=pwhash)
            user = User.objects.last()
            return (flag, user)
        return (flag, errors)
    def userLogin(self, postData):
        user= User.objects.get(email=postData['email'])
        password= postData['password'].encode()
        hashed=user.password.encode()
        if bcrypt.hashpw(password, hashed )== hashed and user:
            return (True, user)
        else:
            return (False, "Email and password do not match")

class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects= UserManager()

myEnvironments/login_and_registrationDjango/apps/loginAndRegistration/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User
import bcrypt

def index(request):
    print User.objects.all()
    if not 'errors' in request.session:
        request.session['errors']=[]
    return render(request, 'loginAndRegistration/index.html')



def process(request):
    postData= {
        "first_name":request.POST['first_name'],
        "last_name": request.POST['last_name'],
        "email": request.POST['email'],
        "password": request.POST['password'],
        "password_confirmation":request.POST['password_confirmation']
    }
    results= User.objects.UserValidator(postData)
    if results[0]:
        for err in results[1]:
            messages.error(request,err)
        return render (request, 'loginAndRegistration/index.html')
    else:
        request.session['loggedinuser']= results[1].id
        # return redirect( '/success')
        return redirect(reverse('success'))


def login(request):
    postData={
        "email": request.POST['email'],
        "password": request.POST['password']
    }
    results = User.objects.userLogin(postData)
    if results == None:
        messages.error(request, "wrong credentials")
        return redirect('/')
    elif results[0]:
        request.session['loggedinuser']= results[1].id
        return redirect(reverse("success"))
    else:
        messages.error(request, results[1])
        return redirect('/')

def success(request):
    context={
        'user': User.objects.get(id=request.session['loggedinuser'])
    }
    return render(request, 'loginAndRegistration/success.html', context)

def delete(request, id):
    if User.objects.filter(id=id).delete():
        return redirect('/')

def logout(request):
    request.session.pop('loggedinuser')
    return redirect("/")

myEnvironments/login_and_registrationDjango/apps/loginAndRegistration/templates/loginAndRegistration/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Login and Registration</title>
    <link rel="stylesheet" href="{% static 'loginAndRegistration/css/loginAndRegistration.css' %}"media="screen"  charset="utf-8">
</head>
<body>
    <div id="wrapper">
        <h1>Login and Registration</h1>
        {% if messages %}
        <ul class="messages">
        {%for message in messages%}
        <li {% if message.tags %} class={{message.tags}} {% endif %}>{{message}}</li>
        {% endfor %}
        </ul>
        {% endif %}
        <h3>Register Below!</h3>
        <form action="{% url 'loginAndRegistration:process' %}" method='post'>
            {% csrf_token %}
            <p>Email: <input class="longer" type='text' name='email' placeholder="enter a valid email address" required></p>
            <p>First Name: <input class="longer" type='text' name='first_name' placeholder="cannot contain numbers" required></p>
            <p>Last Name: <input class="longer" type='text' name='last_name' placeholder="cannot contain numbers" required></p>
            <p>Password: <input class="longer" type='password' name='password' placeholder="must be at least 8 characters" required></p>
            <p>Confirm Password: <input class="longer" type='password' name='password_confirmation' placeholder="must be at least 8 characters" required=""></p>
            <input class="submit" type='submit' value='Create User'>
        </form>
        <h3>Already Registered?</h3>
        <form action="{% url 'loginAndRegistration:login' %}" method='post'>
            {% csrf_token %}
            <p>Email: <input class="longer" type='text' name='email'></p>
            <p>Password: <input class="longer" type='password' name='password'></p>
            <input type='submit' value='Login'>
        </form>
    </div>
</body>
</html>

myEnvironments/login_and_registrationDjango/apps/loginAndRegistration/templates/loginAndRegistration/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course</title>
</head>
<body>
    <div id="container">
        <h1>Success! Welcome, {{user.first_name}}</h1>
        <table>
            <thead>
                <tr>
                <td>First Name</td><td>Last Name</td><td>Email</td>
            </tr>
            </thead>
            <tbody>
                <tr>
                <td>{{user.first_name}}</td><td>{{user.last_name}}</td><td>{{user.email}}</td><td><a href="{% url 'loginAndRegistration:delete' id=user.id %}">Delete</td>
                </tr>
            </tbody>
        </table>
        <a href="{% url 'loginAndRegistration:logout' %}" value="Logout">Log Out </a>

</body>
</html>