myEnvironments/multipleApps/apps/courses/urls.py
from django.conf.urls import url
# from . import views
from views import index, add, course, delete, logout

app_name = 'course'
urlpatterns = [
    url(r'^$', index, name='index_course'),
    url(r'^add$', add, name='add'),
    url(r'^courses/destroy/(?P<id>\d+)$',course, name='course'),
    url(r'^delete/(?P<id>\d+)$',delete, name='delete'),
    url(r'^logout$', logout, name='logout'),
]

myEnvironments/multipleApps/multipleApps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('apps.loginregistration.urls')),
	url(r'^courses/users_courses/', include('apps.courses_users.urls')),
	url(r'^courses/', include('apps.courses.urls')),

]

myEnvironments/multipleApps/apps/courses/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginregistration.models import User

class CourseManager(models.Manager):
    def add_user_to_course(self, form_data):
        print "---Add user----"
        course = self.get(id=form_data['course'])
        print course.name
        print course.id
        user = User.loginMgr.get(id=form_data['user'])
        print user.first_name
     

class Course(models.Model):
	name = models.CharField(max_length = 255)
	description = models.CharField(max_length = 255)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	courseMgr = CourseManager()

myEnvironments/multipleApps/apps/courses/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Course
from ..courses_users.models import User_Course

# Create your views here.
def index(request):
	context = {
	'courses': Course.courseMgr.all()
	}
	return render(request, "courses/index.html", context)

def add(request):
	Course.courseMgr.create(name= request.POST['name'],description=request.POST['description'])
	
	return redirect('/courses')

def course(request, id):
	context = {
	'courses': Course.courseMgr.filter(id=id)
	}
	return render(request, "courses/delete.html", context)

def delete(request, id):
	delete = Course.courseMgr.get(id=id)
	Course.courseMgr.filter(id=id).delete()
	User_Course.user_course_Mgr.filter(course_id=id).delete()
	return redirect('/courses')

def logout(request):
	request.session.pop('user_id')
	request.session.pop('name')
	return redirect('/')

myEnvironments/multipleApps/apps/courses/templates/courses/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Delete a course</title>
	{% load staticfiles %}
  <link rel="stylesheet" href="{% static 'courses_project/css/styles.css' %}">
</head>
<body>
<div id="del_wrapper">
<h1>Are you sure you want to delete the following course??</h1>	
{% for course in courses %}
<h3>Name: {{course.name}}</h3>
<h3>Description: {{course.description}}</h3>
<form action="/courses/" method="POST">
{% csrf_token %}
<input type="submit" name="sumbit" value="No">
</form>
<form action="{% url 'course:delete' id=course.id %}" method="POST">
{% csrf_token %}
<input type="submit" name="sumbit" value="YES!! I want to delete this..">
</form>
{% endfor %}
</div>
</body>
</html>

myEnvironments/multipleApps/apps/courses/templates/courses/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Courses</title>
  <link rel="stylesheet" href="{% static 'courses/css/styles.css' %}">
</head>
<body>
<div id="wrapper">
  	<form action="{% url 'course:logout' %}" class="out" method="post" >
  		<strong>Welcome, {{request.session.name}}</strong>
  		{% csrf_token %}
		<input type="submit" name="logout" value="Log out" class="btn_logout">
  	</form>
<form action="{% url 'course:add' %}" method="POST">
{% csrf_token %}
<h1>Add a new course</h1>
<p>Name: <input type="text" name="name" class="txt_name" required></p>
<p>Description: </p><textarea cols="47" rows="7" name="description"></textarea><br>
<input type="submit" name="submit" value="Add" class="btn_add">
</form>
<div>
<h3>Courses</h3>	 
	<table>
		<tr class="head">
			<th>Course Name</th>
			<th>Description</th>
			<th>Date Added</th>
			<th>Actions</th>
		</tr>
		{% for course in courses %}
		<tr>
			<td>{{course.name}}</td>
			<td>{{course.description}}</td>
			<td>{{course.created_at}}</td>
			<td class="center">
			<form action="{% url 'course:course' id=course.id %}" method="POST">
			{% csrf_token %}
			<input type="submit" name="submit" value="remove">
			</form>
			</td>
		{% endfor %}
		</tr>
	</table>
</div>
<p><a href="/courses/users_courses/">Add Courses to Users</a></p>
</div>
</body>
</html>